set nocompatible
filetype off

call pathogen#infect()


"set rtp+=~/.vim/bundle/vundle
"call vundle#rc()
"Bundle 'gmarik/vundle'
"
"Bundle 'rails.vim'
"Bundle 'vim-coffee-script'
"Bundle 'ctrlp'

filetype plugin indent on

set number
set ruler
syntax on

let g:Powerline_symbols = 'fancy'

" Set encoding
set encoding=utf-8

" Whitespace stuff
set nowrap
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set list listchars=tab:\ \ ,trail:·

" Searching
set hlsearch
set incsearch
set ignorecase
set smartcase

:nnoremap <CR> :nohlsearch<cr>

" Tab completion
set wildmode=list:longest,list:full
set wildignore+=*.o,*.obj,.git,*.rbc,*.class,.svn,vendor/gems/*

" Status bar
set laststatus=2

set scrolloff=3
set autoindent
set showmode
set showcmd
set hidden
set wildmenu
set wildmode=list:longest
set visualbell
set ttyfast
set ruler
set backspace=indent,eol,start
set laststatus=2
" set relativenumber
set noundofile
set wrap
set directory=~/.vim/tmp/

let g:solarized_termcolors=256
set background=dark
colorscheme solarized

" don't clobber buffer if used in term
set t_ti= t_te=

" Make Arrow Keys Useful Again
map <down> <ESC>:bn<RETURN>
map <right> <ESC>:TagbarToggle<RETURN>
map <left> <ESC>:GundoToggle<RETURN>
map <up> <ESC>:bp<RETURN>

imap <C-h> <C-w> h
imap <C-j> <C-w> j
imap <C-k> <C-w> k
imap <C-l> <C-w> l

" Removes trailing spaces
function TrimWhiteSpace()
  %s/\s*$//
  ''
:endfunction

au BufNewFile,BufRead *.less set filetype=css

set list listchars=tab:\ \ ,trail:·,extends:>,precedes:<
"autocmd FileWritePre * :call TrimWhiteSpace()
"autocmd FileAppendPre * :call TrimWhiteSpace()
"autocmd FilterWritePre * :call TrimWhiteSpace()
"autocmd BufWritePre * :call TrimWhiteSpace()

map <F2> :call TrimWhiteSpace()<CR>
map! <F2> :call TrimWhiteSpace()<CR>

let g:github_user = 'trinary'
let g:github_token = '30679f558136f61d4f9694b79b80bc4c'

if has ("gui_mac" ) || has("gui_macvim")
  set guioptions-=T
  set gfn=Menlo\ for\ Powerline:h14
  " Fullscreen takes up entire screen
  set fuoptions=maxhorz,maxvert

  " Command-T for CommandT
  macmenu &File.New\ Tab key=<Nop>
  map <D-t> :CommandT<CR>
  imap <D-t> <Esc>:CommandT<CR>

  " Command-Return for fullscreen
  macmenu Window.Toggle\ Full\ Screen\ Mode key=<D-CR>
endif
